Repository geon-sisters/KpopDanceShoot-Android, pull requests merged in 2021-01, with the labels that each got.

#3 Implement layout of search and bookmark view
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/kpopdance/BookmarkFragment.kt
  app/src/main/java/com/android/kpopdance/BookmarkViewModel.kt
  app/src/main/java/com/android/kpopdance/HomeFragment.kt
  app/src/main/java/com/android/kpopdance/HomeViewModel.kt
  app/src/main/java/com/android/kpopdance/MainActivity.kt
  app/src/main/java/com/android/kpopdance/SearchFragment.kt
  app/src/main/java/com/android/kpopdance/SearchViewModel.kt
  app/src/main/java/com/android/kpopdance/Youtube.kt
  app/src/main/java/com/android/kpopdance/YoutubeSmallAdapter.kt
  app/src/main/res/drawable/ic_home_black_24dp.xml
  app/src/main/res/drawable/ic_reorder_black_24dp.xml
  app/src/main/res/drawable/ic_search_black_24dp.xml
  app/src/main/res/drawable/ic_star_black_24dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/bookmark_fragment.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/layout/youtube_small_item.xml
  app/src/main/res/menu/bottom_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#4 Implement drawerLayout in search view
  app/src/main/java/com/android/kpopdance/BookmarkFragment.kt
  app/src/main/java/com/android/kpopdance/SearchFragment.kt
  app/src/main/java/com/android/kpopdance/SingerAdapter.kt
  app/src/main/res/drawable/singer_button_selector.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/layout/singer_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#5 Implement Home Layout
  app/src/main/java/com/android/kpopdance/HomeFragment.kt
  app/src/main/java/com/android/kpopdance/YoutubeBigAdapter.kt
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/youtube_big_item.xml
Labels: enhancement

#6 Implement Advertisements
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/kpopdance/BookmarkFragment.kt
  app/src/main/java/com/android/kpopdance/HomeFragment.kt
  app/src/main/java/com/android/kpopdance/MainActivity.kt
  app/src/main/java/com/android/kpopdance/SearchFragment.kt
  app/src/main/java/com/android/kpopdance/YoutubeBigAdapter.kt
  app/src/main/res/layout/bookmark_fragment.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/layout/youtube_big_item.xml
  build.gradle
Labels: enhancement

#7 Refactor packages
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/kpopdance/data/Youtube.kt
  app/src/main/java/com/android/kpopdance/ui/BookmarkFragment.kt
  app/src/main/java/com/android/kpopdance/ui/HomeFragment.kt
  app/src/main/java/com/android/kpopdance/ui/MainActivity.kt
  app/src/main/java/com/android/kpopdance/ui/SearchFragment.kt
  app/src/main/java/com/android/kpopdance/ui/SingerAdapter.kt
  app/src/main/java/com/android/kpopdance/ui/YoutubeBigAdapter.kt
  app/src/main/java/com/android/kpopdance/ui/YoutubeSmallAdapter.kt
  app/src/main/java/com/android/kpopdance/viewmodel/BookmarkViewModel.kt
  app/src/main/java/com/android/kpopdance/viewmodel/HomeViewModel.kt
  app/src/main/java/com/android/kpopdance/viewmodel/SearchViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/bookmark_fragment.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/layout/youtube_big_item.xml
  app/src/main/res/layout/youtube_small_item.xml
Labels: refactoring

#8 Implement binding with view and viewmodel of home
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/kpopdance/App.kt
  app/src/main/java/com/android/kpopdance/AppModule.kt
  app/src/main/java/com/android/kpopdance/HomeBindingAdapters.kt
  app/src/main/java/com/android/kpopdance/data/Youtube.kt
  app/src/main/java/com/android/kpopdance/model/YoutubeApi.kt
  app/src/main/java/com/android/kpopdance/repository/YoutubeRepository.kt
  app/src/main/java/com/android/kpopdance/ui/BookmarkFragment.kt
  app/src/main/java/com/android/kpopdance/ui/HomeFragment.kt
  app/src/main/java/com/android/kpopdance/ui/SearchFragment.kt
  app/src/main/java/com/android/kpopdance/ui/YoutubeBigAdapter.kt
  app/src/main/java/com/android/kpopdance/viewmodel/BaseViewModel.kt
  app/src/main/java/com/android/kpopdance/viewmodel/HomeViewModel.kt
  app/src/main/res/layout/bookmark_fragment.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/layout/youtube_big_item.xml
  build.gradle
Labels: enhancement

#9 Implement click event of BigYoutube item
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/kpopdance/contract/Contract.kt
  app/src/main/java/com/android/kpopdance/ui/DanceActivity.kt
  app/src/main/java/com/android/kpopdance/ui/HomeFragment.kt
  app/src/main/java/com/android/kpopdance/ui/MainActivity.kt
  app/src/main/java/com/android/kpopdance/viewmodel/BaseViewModel.kt
  app/src/main/java/com/android/kpopdance/viewmodel/Event.kt
  app/src/main/java/com/android/kpopdance/viewmodel/HomeViewModel.kt
  app/src/main/res/layout/activity_dance.xml
  app/src/main/res/layout/youtube_big_item.xml
Labels: enhancement, refactoring

#10 Implement logic of search
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/kpopdance/AppModule.kt
  app/src/main/java/com/android/kpopdance/HomeBindingAdapters.kt
  app/src/main/java/com/android/kpopdance/adapter/BindingAdapters.kt
  app/src/main/java/com/android/kpopdance/model/YoutubeApi.kt
  app/src/main/java/com/android/kpopdance/repository/YoutubeRepository.kt
  app/src/main/java/com/android/kpopdance/ui/BaseFragment.kt
  app/src/main/java/com/android/kpopdance/ui/BookmarkFragment.kt
  app/src/main/java/com/android/kpopdance/ui/BookmarkYoutubeAdapter.kt
  app/src/main/java/com/android/kpopdance/ui/HomeFragment.kt
  app/src/main/java/com/android/kpopdance/ui/HomeYoutubeAdapter.kt
  app/src/main/java/com/android/kpopdance/ui/SearchFragment.kt
  app/src/main/java/com/android/kpopdance/ui/SearchYoutubeAdapter.kt
  app/src/main/java/com/android/kpopdance/viewmodel/BaseViewModel.kt
  app/src/main/java/com/android/kpopdance/viewmodel/HomeViewModel.kt
  app/src/main/java/com/android/kpopdance/viewmodel/SearchViewModel.kt
  app/src/main/res/layout/bookmark_fragment.xml
  app/src/main/res/layout/bookmark_youtube_item.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/home_youtube_item.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/layout/search_youtube_item.xml
Labels: enhancement, refactoring

#11 Implement logic of bookmark
  app/build.gradle
  app/src/main/java/com/android/kpopdance/App.kt
  app/src/main/java/com/android/kpopdance/AppModule.kt
  app/src/main/java/com/android/kpopdance/adapter/BindingAdapters.kt
  app/src/main/java/com/android/kpopdance/model/AppDatabase.kt
  app/src/main/java/com/android/kpopdance/model/Bookmark.kt
  app/src/main/java/com/android/kpopdance/model/BookmarkDao.kt
  app/src/main/java/com/android/kpopdance/repository/BookmarkRepository.kt
  app/src/main/java/com/android/kpopdance/repository/YoutubeRepository.kt
  app/src/main/java/com/android/kpopdance/ui/BookmarkFragment.kt
  app/src/main/java/com/android/kpopdance/ui/BookmarkYoutubeAdapter.kt
  app/src/main/java/com/android/kpopdance/ui/HomeFragment.kt
  app/src/main/java/com/android/kpopdance/viewmodel/BaseViewModel.kt
  app/src/main/java/com/android/kpopdance/viewmodel/BookmarkViewModel.kt
  app/src/main/java/com/android/kpopdance/viewmodel/HomeViewModel.kt
  app/src/main/java/com/android/kpopdance/viewmodel/SearchViewModel.kt
  app/src/main/res/layout/bookmark_fragment.xml
  app/src/main/res/layout/bookmark_youtube_item.xml
  app/src/main/res/layout/home_youtube_item.xml
  app/src/main/res/layout/search_youtube_item.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#12 Implement DanceYoutube Layout
  app/build.gradle
  app/libs/YouTubeAndroidPlayerApi.jar
  app/src/main/java/com/android/kpopdance/ui/DanceActivity.kt
  app/src/main/res/layout/activity_dance.xml
  app/src/main/res/layout/bookmark_youtube_item.xml
  app/src/main/res/layout/home_youtube_item.xml
  app/src/main/res/layout/search_youtube_item.xml
Labels: enhancement

#13 Implement Loading Layout and Font
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/kpopdance/ui/LoadingActivity.kt
  app/src/main/java/com/android/kpopdance/ui/MainActivity.kt
  app/src/main/res/font/cafe24dangdanghae.ttf
  app/src/main/res/font/font.xml
  app/src/main/res/layout/activity_loading.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#14 Implement Draft of Dance Portrait UI
  app/build.gradle
  app/libs/YouTubeAndroidPlayerApi.jar
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/kpopdance/ui/AlbumFragment.kt
  app/src/main/java/com/android/kpopdance/ui/BaseFragment.kt
  app/src/main/java/com/android/kpopdance/ui/CameraFragment.kt
  app/src/main/java/com/android/kpopdance/ui/DanceActivity.kt
  app/src/main/java/com/android/kpopdance/ui/DancePortraitActivity.kt
  app/src/main/java/com/android/kpopdance/ui/QuickSearchAdapter.kt
  app/src/main/java/com/android/kpopdance/ui/SearchFragment.kt
  app/src/main/java/com/android/kpopdance/viewmodel/BaseViewModel.kt
  app/src/main/java/com/android/kpopdance/viewmodel/HomeViewModel.kt
  app/src/main/java/com/android/kpopdance/viewmodel/SearchViewModel.kt
  app/src/main/res/drawable/ic_video_library_black_24dp.xml
  app/src/main/res/drawable/ic_videocam_black_24dp.xml
  app/src/main/res/layout/activity_dance.xml
  app/src/main/res/layout/activity_dance_portrait.xml
  app/src/main/res/layout/bookmark_youtube_item.xml
  app/src/main/res/layout/fragment_album.xml
  app/src/main/res/layout/fragment_camera.xml
  app/src/main/res/layout/home_youtube_item.xml
  app/src/main/res/layout/quick_search_item.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/layout/search_youtube_item.xml
  app/src/main/res/menu/dance_menu.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement
